---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-pv-nfs
  namespace: transmission
  labels:
    bucket: shared
spec:
  capacity:
    storage: 4T
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: transmission
    name: transmission-pvc
  nfs:
    server: {{ nfs_server_ip }}
    path: "/home/pi/nas/transmission"
