---
- name: Deploy Kubernetes resources via master node.
  hosts: main
  gather_facts: false

  collections:
    - community.kubernetes

  environment:
    # The location of the kubeconfig file on the master.
    K8S_AUTH_KUBECONFIG: ~/.kube/config
    PATH: "~/go/bin:{{ ansible_env.PATH }}"

  roles:
    - role: setup
      tags: ['setup']

    - role: cluster_monitoring
      tags: ['monitoring', 'prometheus']

    - role: infothrill.rpi_boot_config
      boot_config_lines: ['gpu_mem=16'] 
      tags: ['rpi_boot_config']

#    - role: drupal
#      tags: ['drupal']

#    - role: wordpress
#      tags: ['wordpress']

#    - role: minecraft
#      tags: ['minecraft']

#    - role: pihole
#      tags: ['pihole']

#    - role: status
#      tags: ['status', 'debug']
