---
- name: Deploy Kubernetes resources via master node.
  hosts: turing-main
  gather_facts: false

  collections:
    - community.kubernetes

  environment:
    # The location of the kubeconfig file on the master.
    K8S_AUTH_KUBECONFIG: ~/.kube/config
    PATH: "~/go/bin:{{ ansible_env.PATH }}"

  roles:
    - role: setup
      tags: ['setup']

    - role: cluster_monitoring
      tags: ['monitoring', 'prometheus']

    - name: Turning on power LED
      role: infothrill.rpi_boot_config
      boot_config_lines:
      - gpio=17=op,dh
      tags: ['turing-main_boot_config']

#    - role: drupal
#      tags: ['drupal']

#    - role: wordpress
#      tags: ['wordpress']

#    - role: minecraft
#      tags: ['minecraft']

#    - role: pihole
#      tags: ['pihole']

#    - role: status
#      tags: ['status', 'debug']

- name: Deploy I2C
  hosts: k3s_cluster

  roles:
    - name: Turning on I2C
      role: infothrill.rpi_boot_config
      boot_config_lines: 
      - dtoverlay=i2c1,pins_44_45
      - dtoverlay=i2c-rtc,mcp7940x
      - gpu_mem=16
      tags: ['cluster_boot_config']
