---
- name: Set up cluster-wide configuration.
  hosts: k3s_cluster
  become: true

  tasks: []

- name: Deploy Kubernetes resources via master node.
  hosts: master
  gather_facts: false

  vars:
    unifi_poller: false
    monitoring_namespace: monitoring

  collections:
    - community.kubernetes

  environment:
    # The location of the kubeconfig file on the master.
    K8S_AUTH_KUBECONFIG: ~/.kube/config
    PATH: "~/go/bin:{{ ansible_env.PATH }}"

  roles:
    - role: setup
      tags:
        - setup
        - homebridge
        - transmission

#    - role: unifi_poller
#      tags: ['unifi-poller']
#      when: unifi_poller | bool

#    - role: cluster_monitoring
#      tags: ['monitoring', 'prometheus']

    - role: homebridge
      tags: ['homebridge']

    - role: transmission
      tags: ['transmission']

    - role: installer
      tags: ['installer']

    - role: gotify
      tags: ['gotify']

    - role: diun
      tags: ['diun']

#    - role: pihole
#      tags: ['pihole']

    - role: status
      tags: ['status', 'debug']
