---
- name: Create monitoring namespace.
  k8s:
    name: "{{ monitoring_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Add k8s-at-home chart repo.
  helm_repository:
    name: k8s-at-home
    repo_url: "https://k8s-at-home.com/charts/"

- name: Deploy unifi-poller Helm chart.
  helm:
    name: unifi-poller
    chart_ref: k8s-at-home/unifi-poller
    chart_version: "{{ unifi_poller_chart_version }}"
    release_namespace: "{{ monitoring_namespace }}"
    state: present
    values:
      prometheus:
        serviceMonitor:
          enabled: true
          interval: 1m
          additionalLabels: {}
      config:
        unifi:
          dynamic: false
          defaults:
            role: "main controller"
            user: "{{ unifi_user }}"
            pass: "{{ unifi_pass }}"
            url: "{{ unifi_url }}"
            sites:
              - all
            verify_ssl: false
            save_ids: true
            save_dpi: true
            save_sites: true
          controllers: []
