apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f dc.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: transmission
  name: transmission
  namespace: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: transmission
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f dc.yaml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: transmission
    spec:
      containers:
      - env:
        - name: PASS
          value: hypriot
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TRANSMISSION_WEB_HOME
          value: /combustion-release/
        - name: TZ
          value: Europe/London
        - name: USER
          value: pirate
        image: linuxserver/transmission:arm32v7-latest
        imagePullPolicy: ""
        name: transmission
        ports:
        - containerPort: 9091
        - containerPort: 51413
        - containerPort: 51413
          protocol: UDP
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /downloads
          name: downloads
        - mountPath: /watch
          name: watch
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /config
          type: ""
        name: config
      - name: downloads
        nfs:
          path: /home/pi/nas/downloads
          server: 192.168.1.192
      - hostPath:
          path: /watch
          type: ""
        name: watch
      
status: {}
