---
- name: Create minecraft namespace.
  k8s:
    name: minecraft
    api_version: v1
    kind: Namespace
    state: present

- name: Add itzg chart repo.
  helm_repository:
    name: itzg
    repo_url: "https://itzg.github.io/minecraft-server-charts/"

- name: Deploy Minecraft Helm chart.
  helm:
    name: minecraft
    chart_ref: itzg/minecraft
    chart_version: '2.0.7'
    release_namespace: minecraft
    state: present
    values:
      imageTag: multiarch
      livenessProbe:
        initialDelaySeconds: 60
        periodSeconds: 10
        failureThreshold: 180
      readinessProbe:
        initialDelaySeconds: 60
        periodSeconds: 10
        failureThreshold: 180
      minecraftServer:
        eula: true
        version: "LATEST"
        Difficulty: easy
        motd: "Welcome to Minecraft on Turing Pi!"
        # These settings should help the server run better on underpowered Pis.
        maxWorldSize: 5000
        viewDistance: 6
