---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.1.0/24
  name: homebridge
  namespace: homebridge
spec:
  rules:
  - host: homebridge.192.168.1.202.nip.io
    http:
      paths:
      - backend:
          serviceName: homebridge
          servicePort: 8080
