---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-pvc
  namespace: homebridge
spec:
  selector:
    matchLabels:
      bucket: shared
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1T
