---
- name: Create transmission namespace.
  k8s:
    name: transmission
    api_version: v1
    kind: Namespace
    state: present

- name: Add nicholaswilde chart repo.
  kubernetes.core.helm_repository:
    name: nicholaswilde
    repo_url: "https://nicholaswilde.github.io/helm-charts/"

- name: Deploy transmission Helm chart.
  kubernetes.core.helm:
    name: transmission
    chart_ref: nicholaswilde/transmission
    chart_version: '{{ transmission_chart_version }}'
    release_namespace: transmission
    update_repo_cache: yes
    state: present
    values:
      config:
        transmission_web_home: "/kettu/"
        tz: "{{ timezone }}"
      persistence:
        downloads:
          enabled: true
          storageClass: "{{ storage_class }}"
      ingress:
        enabled: true
        hosts:
          - host: "transmission.{{ ingress_server_ip }}.nip.io"
            paths: [/]
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
