---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: unifi-poller
  namespace: monitoring
spec:
  rules:
  - host: unifi-poller.192.168.1.202.nip.io
    http:
      paths:
      - backend:
          serviceName: unifi-poller
          servicePort: http
        path: /
  tls:
  - hosts:
    - unifi-poller.192.168.1.202.nip.io
