---
prometheus:
  serviceMonitor:
    enabled: true
    interval: 1m
    additionalLabels: {}

config:
  unifi:
    dynamic: false
    defaults:
      role: "main controller"
      user: "unifipoller"
      pass: "unifipoller"
      url: "https://192.168.1.148:8443"
      sites:
        - all
      verify_ssl: false
      save_ids: true
      save_dpi: true
      save_sites: true
    controllers: []
