---
- name: Ensuring apt caches are up to date.
  apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Ensuring required dependencies are installed.
  package:
    name:
      - python3-pip
      - python3-setuptools
      - build-essential
      - golang
      - git
      - i2c-tools
    state: present
  become: true

- name: Ensuring openshift Python library is installed.
  pip:
    name: openshift
    state: present
  become: true
