---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homebridge-pv-nfs
  labels:
    bucket: shared
spec:
  capacity:
    storage: 4T
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: homebridge
    name: homebridge-pvc
  nfs:
    server: {{ nfs_server_ip }}
    path: {{ homebridge_nfs_path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-pvc
  namespace: homebridge
spec:
  selector:
    matchLabels:
      bucket: shared
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1T

